### PR TITLE
Fixed UI input when a viewport is applied (fixes #89)

### LINKED ISSUE #89: UI input doesn't work inside viewport
Input coordinates aren't properly scaled if the ui is rendered inside a viewport

### PR DESCRIPTION
**Pull request by augustozanellato**
Also fixed failing tests in LibgdxGraphicsTest

### CODE REVIEW

File: ui/src/main/java/org/mini2Dx/ui/UiContainer.java [hunk 1]
```diff
@@ -321,8 +325,13 @@ public boolean touchDown(int screenX, int screenY, int pointer, int button) {
 		if (!pointerNavigationAllowed()) {
 			return false;
 		}
-		screenX = MathUtils.round(screenX / scaleX);
-		screenY = MathUtils.round(screenY / scaleY);
+		if (viewport != null) {
+			sharedVector.x = screenX;
+			sharedVector.y = screenY;
+			viewport.toWorldCoordinates(sharedVector);
+			screenX = (int) sharedVector.x;
```
Comment (tomcashman) [inline ui/src/main/java/org/mini2Dx/ui/UiContainer.java]: Use ```MathUtils.round``` here

File: ui/src/main/java/org/mini2Dx/ui/UiContainer.java [hunk 2]
```diff
@@ -384,8 +398,13 @@ public boolean touchDragged(int screenX, int screenY, int pointer) {
...
```
Comment (tomcashman) [inline ui/src/main/java/org/mini2Dx/ui/UiContainer.java]: MathUtils.round
