### PR TITLE
Fix cursor hiding on LWJGL3, closes #270

### LINKED ISSUE #270: Fix hiding custom cursor on lwjgl 3 runtime
See https://github.com/libgdx/libgdx/issues/5546

### PR DESCRIPTION
**Pull request by augustozanellato**

### CODE REVIEW

File: libgdx-desktop-lwjgl3/src/main/java/org/mini2Dx/libgdx/desktop/Lwjgl3CustomCursor.java [hunk 1]
```diff
@@ -0,0 +1,29 @@
+package org.mini2Dx.libgdx.desktop;
```
Comment (tomcashman) [inline libgdx-desktop-lwjgl3/src/main/java/org/mini2Dx/libgdx/desktop/Lwjgl3CustomCursor.java:1]: Missing license header
